const vocaro_value_list = [
    "adachi-rei",
    "akita-neru",
    "amaga-eru",
    "anna-nyui",
    "anon-kanon",
    "anone-izumu",
    "aoki-lapis",
    "ario",
    "arsloid",
    "asane-bou",
    "asane-emma",
    "avanna",
    "azuki",
    "chika",
    "chis-a",
    "coko",
    "daina",
    "denka-sen",
    "dex",
    "fukase",
    "gekiyaku",
    "gumi",
    "gyarako",
    "hakaine-maiko",
    "haruno-sora",
    "hatsune-miku",
    "hiyama-kiyoteru",
    "ia",
    "jsut",
    "kaai-yuki",
    "kafu",
    "kagamine-len",
    "kagamine-rin",
    "kaito",
    "kamui-gakupo",
    "kaori",
    "kasane-teto",
    "kazehiki",
    "kemonone-rou",
    "ken",
    "kizuna-akari",
    "koharu-rikka",
    "kokone",
    "kotonoha-akane",
    "kotonoha-aoi",
    "kuon-bushi",
    "kuzuda-yone",
    "lily",
    "lumi",
    "luo-tianyi",
    "makimiya-huuki",
    "makune-nana",
    "matcha",
    "matsuda-poine",
    "matsuda-poiyo",
    "mayu",
    "megurine-luka",
    "meika-hime",
    "meika-mikoto",
    "meiko",
    "mew",
    "mine-laru",
    "momone-momo",
    "namine-litsu",
    "natsuki-karin",
    "necomura-iroha",
    "neumafu",
    "nigimine-kakoi",
    "oliver",
    "one",
    "otama-boushi",
    "otomachi-una",
    "ouka-alice",
    "rana",
    "rime",
    "sachiko",
    "saine-yume",
    "sakane-cecil",
    "saki",
    "samune-zimi",
    "sato-sasara",
    "seeu",
    "sekai",
    "setka-yufu",
    "sf-a2-devcode-miki",
    "shikirine-kuroku",
    "shione-luto",
    "soune-renji",
    "sukone-tei",
    "tohokou-zunko",
    "tohoku-itako",
    "tohoku-kiritan",
    "tohoku-yoko",
    "tone-rion",
    "touka-hako",
    "tsumitsugu-nae",
    "tsurumaki-maki",
    "uni-vocaloid",
    "utane-uta",
    "utatane-piko",
    "v-flower",
    "vy1",
    "vy2",
    "xin-hua",
    "yamine-renri",
    "yohioloid",
    "yowane-haku",
    "yuzuki-yukari",
    "zola-project",
];
const vocaro_label_list = [
    "아다치 레이",
    "아키타 네루",
    "아마가 에루",
    "안나 뉴이",
    "아논 카논",
    "아노네 이즈무",
    "아오키 라피스",
    "아리오",
    "아르스로이드",
    "아사네 보우",
    "아사네 엠마",
    "AVANNA",
    "AZUKI",
    "chika",
    "치세이",
    "코코",
    "Daina",
    "덴카 센",
    "Dex",
    "Fukase",
    "게키야쿠",
    "GUMI",
    "갸라코",
    "하카이네 마이코",
    "하루노 소라",
    "하츠네 미쿠",
    "히야마 키요테루",
    "IA",
    "JSUT",
    "카아이 유키",
    "카후",
    "카가미네 렌",
    "카가미네 린",
    "KAITO",
    "카무이 가쿠포",
    "Kaori",
    "카사네 테토",
    "카제히키",
    "케모노네 로우",
    "Ken",
    "키즈나 아카리",
    "코하루 릿카",
    "kokone",
    "코토노하 아카네",
    "코토노하 아오이",
    "쿠온 부시",
    "쿠즈다 요네",
    "Lily",
    "LUMi",
    "뤄톈이",
    "마키미야 후키",
    "마쿠네 나나",
    "MATCHA",
    "마츠다 포이네",
    "마츠다 포이요",
    "MAYU",
    "메구리네 루카",
    "메이카 히메",
    "메이카 미코토",
    "MEIKO",
    "Mew",
    "미네 라루",
    "모모네 모모",
    "나미네 리츠",
    "나츠키 카린",
    "네코무라 이로하",
    "네우마후",
    "니지미네 카코이",
    "OLIVER",
    "ONE",
    "오타마 보오시",
    "오토마치 우나",
    "오오카 아리스",
    "Rana",
    "리메",
    "Sachiko",
    "사이네 유메",
    "사카네 세실",
    "Saki",
    "사무네 지미",
    "사토 사사라",
    "시유",
    "세카이",
    "셋카 유후",
    "SF-A2 개발코드 miki",
    "시키리네 쿠로쿠",
    "시오네 루토",
    "소오네 렌지",
    "스코네 테이",
    "토호쿠 즌코",
    "AI 이타코",
    "토호쿠 키리탄",
    "AI 요코",
    "토네 리온",
    "토오카 하코",
    "츠미츠구 나에",
    "츠루마키 마키",
    "유니",
    "우타네 우타",
    "우타타네 피코",
    "v flower",
    "VY1",
    "VY2",
    "신화",
    "야미네 렌리",
    "YOHIOloid",
    "요와네 하쿠",
    "유즈키 유카리",
    "ZOLA PROJECT",
];
